az_prefix      = "dv_aztf_slzrcloud_"
prefix         = "dv0aztf0slzr0cloud0"
prefix_k8s     = "dv-aztf-slzrcloud"
dns_names      = ["slzr.cloud", "*.slzr.cloud"]
azurelocation  = "eastus"
managed        = "true"
level          = "dev"
address_space  = ["10.20.0.0/16"]
subnet_workers = ["10.20.0.0/24"]
subnet_vip     = ["10.20.1.0/24"]
subnet_appgw   = ["10.20.2.0/24"]
subnet_lb      = ["10.20.3.0/24"]
auth_ip        = ["204.60.15.0/32"]
certname       = "k8-linux-key"
public_ssh_key = "../certificates/k8_privatekey.pub"
private_ssh_key = "../certificates/k8_privatekey"
